[build]
builder = "NIXPACKS"
buildCommand = "cd ravan-backend && npm run build"

[deploy]
startCommand = "cd ravan-backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments]
  [environments.production]
  PORT = "3001"
